### ISSUE TITLE
Ongoing -- Ways to make Dapp faster

### ISSUE THREAD

**Issue by themandalore** [DecentralizedDerivatives/DRCT_standard_DApp#190]
Loading takes a while.  This issue board can serve as a way to throw out ideas to potentially speed things up

**Comment by rayGreycloud** [comment]
I think using Redux Saga instead of Redux Thunk would improve performance. I've read that other Dapps are using Redux Saga on the front end because it's much better at managing async data flows. It also has a feature that prevents repeat data calls while one is pending. That could be helpful in controlling the fireworks caused when components update.
